import type { Metadata } from "next";
import "./globals.css";
import { Sidebar } from "./components/organisms/Sidebar";
import { ThemeProvider } from "@/components/theme-provider";
import Header from "./components/organisms/Header";

export const metadata: Metadata = {
  title: "GBF DB",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <div className="flex flex-col min-h-screen">
            <Header />
            <main>
              <div className="mx-auto">
                <div className="flex">
                  <Sidebar />
                  <main className="md:ml-14 lg:ml-64 w-full">
                    <div className="c-container mx-auto">{children}</div>
                  </main>
                </div>
              </div>
            </main>
            <footer></footer>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
